/******************************************************************************************************
Developed By: OnActuate
Class Name: OA_Constant
Class Purpose: Class which will contain all the Constants being used in the application
Versions: 1.1
******************************************************************************************************/
public class OA_Constant {
    
    public static final String DELIVERY = 'Delivery';
    public static final String INVOICE = 'Invoice';
    public static final String REVENUEFORECASTAPINAME = 'OA_Revenue_Forecast__c';
    public static final String CLOSEDWON = 'Closed Won';

}